clear;                                                                                                           
fs.randSeed(2);                                                                                                  
B=obj_Box;                                                                                                       
B.name='step';                                                                                                   
B.GPUstatus='on';                                                                                                
B.ballR=0.0006;                                                                                                  
B.isClump=0;                                                                                                     
B.distriRate=0.6;                                                                                                
B.sampleW=0.12;                                                                                                  
B.sampleL=0;                                                                                                     
B.sampleH=0.12;                                                                                                  
B.type='topPlaten';                                                                                              
B.setType();                                                                                                     
B.buildInitialModel();                                                                                           
B.setUIoutput();                                                                                                 
d=B.d;                                                                                                           
B.gravitySediment();                                                                                             
B.compactSample(2);                                                                                              
d.clearData(1);                                                                                                  
d.recordCalHour('Step1Finish');                                                                                  
save(['TempModel/' B.name '1.mat'],'B','d');                                                                     
save(['TempModel/' B.name '1R' num2str(B.ballR) '-distri' num2str(B.distriRate)  'aNum' num2str(d.aNum) '.mat']);
d.calculateData();                                                                                               
    d.show('aR');                                                                                                